Develop
bobavtokom/travelWebApp pull request #3
Opened 2023-06-13 22:13 UTC by bobavtokom

2023-06-13 23:31 UTC, nakovz commented on views/pages/login.ejs
> +      <span class="js-include-html" data-filename="partial/_sidebar.htm" data-function="InitSidebar()"></span>
Ovie <span> tagovi ne se vekje potrebni, tie bea za impot na partial views vo prethodniot proekt bez node.js

2023-06-13 23:38 UTC, nakovz requested changes
Potebni se mali izmeni pred merge,
prvata i pobitna e ova so default-nite vrednosti vo Schema-ta vo destinationModel.js
i drugi izmeni e da se trgnat <span> tagovite koi se koristea za import na partial datotekite vo prethodniot proekt

2023-06-13 23:38 UTC, nakovz commented on models/destinationModel.js
Vo schema-ta treba da gi ima i default-nite vrednosti za da pri kreiranje na zapis vo MongoDB da gi vkluci i tie elementi od shemata.

2023-06-14 04:53 UTC, bobavtokom commented on models/destinationModel.js
You have right Zoki i agree with you , i had some issues regarding this file and still shows some errors when trying to merge any branch into develop , 
So thats why i created new model which is the same one only without validations because i couldnt see the exact ones in the moment and i had intention to add them back soon as i found them .
So thanks for the comment and 
Feel free to add those changes that are considered as the right solution 😊

2023-06-14 04:54 UTC, merged